name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{matrix.compat.os}}
    name: OTP ${{matrix.compat.otp}} / Elixir ${{matrix.compat.elixir}}
    strategy:
      matrix:
        compat:
          - otp: '24.2'
            elixir: '1.12'
            os: ubuntu-22.04
          - otp: '28'
            elixir: '1.19'
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.compat.otp}}
          elixir-version: ${{matrix.compat.elixir}}
      - name: Install FFmpeg
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq ffmpeg
      - run: mix deps.get
      - run: mix test
